ucp:
  name: base

  net: "default"
  scaler: "default"
  metric: "KL_sym"
  periods: 1
  window_size: 2
  lag_size: 5
  step: 10
  n_epochs: 100
  lr: 0.01
  lam: 0.0001 
  optimizer: "Adam" 
  alpha: 0.5